MVCBlog/MVCBlog.Web/Controllers/PostInfoController.cs
using MVCBlog.Common;
using MVCBlog.Entities.Models;
using MVCBlog.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVCBlog.Web.Controllers
{
    [AllowAnonymous]
    public class PostInfoController : Controller
    {
        private readonly IPostService postService;
        private readonly IUserService userService;
        private readonly ICategoryService categoryService;
        public PostInfoController(IPostService _postService, IUserService _userService, ICategoryService _categoryService)
        {
            postService = _postService;
            userService = _userService;
            categoryService = _categoryService;
        }
        // GET: PostInfo
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult RecentPost()
        {
            var recentpost = postService.GetRecentPost(ConfigInfo.RecentPostCount);
            return PartialView(recentpost);
        }

        public ActionResult PostCategoryInfo()
        {
            var categorylist = categoryService.Query();
            return PartialView(categorylist);
        }

        public ActionResult PostInfo(int id)
        {
            var entity = postService.GetById(id);
            return View(entity);
        }

        public ActionResult PostMonthList()
        {
            var posttimes = postService.GetPostMonthInfos();
            var times = posttimes.Select(x => x.ToString("yyyy-MM")).Distinct();
            return PartialView(times);
        }
        public ActionResult PostMonthInfo(int year, int month, int index = 1)
        {
            var postinfo = postService.Query(index, ConfigInfo.PageCount, x => x.CreateTime.Year == year && x.CreateTime.Month == month);
            return View(postinfo);
        }

        public ActionResult PostMetaInfo(PostInfo info)
        {
            return PartialView(info);
        }
    }
}

MVCBlog/MVCBlog.Web/Controllers/UserController.cs
using MVCBlog.Common;
using MVCBlog.Entities.Models;
using MVCBlog.Service;
using MVCBlog.Service.Interfaces;
using MVCBlog.Web.CommonHelper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVCBlog.Web.Controllers
{
    //[Authorize]
    public class UserController : Controller
    {
        private IUserService userService;
        private IPostService postService;
        public UserController(IUserService _userService, IPostService _postService)
        {
            userService = _userService;
            postService = _postService;
        }

        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserList()
        {
            return View();
        }

        public ActionResult UserWightInfo()
        {
            UserInfo userinfo = UserHelper.GetLogInUserInfo();
            if (userinfo != null)
            {
                return PartialView(userinfo);
            }
            return PartialView();
        }

        public ActionResult UserPostInfo(int userid, int index = 1)
        {
            var postinfos = postService.Query(index, ConfigInfo.PageCount, x => x.PostAuthor.Id == userid);
            return View(postinfos);
        }
    }
}

MVCBlog/MVCBlog.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="~/Content/js/jquery-2.1.3.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <link href="~/Content/admin/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <!--[if lt IE 9]>
        <script src="~/Content/admin/js/html5.js"></script>
    <![endif]-->
    <link href="~/Content/admin/css/styles.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">逝去日子的博客</a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @foreach (var item in MVCBlog.Web.CommonHelper.Menu.MenuHelper.GetMenuInfo(MVCBlog.Entities.Enums.MenuType.后台))
                    {
                        <li><a href="@item.MenuUrl">@item.MenuName</a></li>
                    }
                    @*<li><a href="#">Dashboard</a></li>
                        <li><a href="#">Settings</a></li>
                        <li><a href="#">Profile</a></li>
                        <li><a href="#">Help</a></li>*@
                </ul>
                @*<form class="navbar-form navbar-right">
                        <input type="text" class="form-control" placeholder="Search...">
                    </form>*@
            </div>
        </div>
    </nav>
    <div class="container-fluid">

        <div class="row row-offcanvas row-offcanvas-left"> 

            <div class="col-sm-9 col-md-10 main">

                <!--toggle sidebar button-->
                <p class="visible-xs">
                    <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas"><i class="glyphicon glyphicon-chevron-left"></i></button>
                </p>

                @RenderBody()

            </div><!--/row-->
        </div>
    </div><!--/.container-->
    <footer>
        @*<p class="pull-right">©2014 Company</p>*@
    </footer>

    <!-- script references -->
    <script src="~/Content/js/jquery-2.1.3.min.js"></script>
    <script src="~/Content/admin/js/bootstrap.min.js"></script>
    <script src="~/Content/admin/js/scripts.js"></script>
</body>
</html>

MVCBlog/MVCBlog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Content/css/pace.css">
    <link rel="stylesheet" href="~/Content/css/custom.css">

    <!-- js -->
    <script src="~/Content/js/jquery-2.1.3.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/pace.min.js"></script>
    <script src="~/Content/js/modernizr.custom.js"></script>
</head>

<body>
    <div class="container">
        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1><a href="@Url.Action("Index","Home")">逝去日子的博客</a></h1>
                    </div>
                </div><!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
                                <li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
                                <li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
                                <li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>
                    <div id="header-search-box">
                        <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                        <div id="search-form" class="search-form">
                            <form role="search" method="get" id="searchform" action="#">
                                <input type="search" placeholder="Search" required>
                                <button type="submit"><span class="ion-ios-search-strong"></span></button>
                            </form>
                        </div>
                    </div>
                </div><!-- col-md-8 -->
            </div>
        </header>
    </div>
    <div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>

    <div class="content-body">
        <div class="container">
            <div class="row">
                @RenderBody()

                <aside class="col-md-4">
                    @Html.Action("UserWightInfo", "User")


                    <div class="widget widget-recent-posts"> 
                        @Html.Action("RecentPost", "PostInfo") 
                    </div>
                  
                    <div class="widget widget-archives">
                        <h3 class="widget-title">Archives</h3>
                        <ul>
                            <li>
                                <a href="#">November 2014</a>
                            </li>
                            <li>
                                <a href="#">September 2014</a>
                            </li>
                            <li>
                                <a href="#">January 2013</a>
                            </li>
                        </ul>
                    </div>
                    @Html.Action("PostCategoryInfo", "PostInfo")
                    @Html.Action("PostMonthList", "PostInfo")
                    @*<div class="widget widget-category">
                            <h3 class="widget-title">Category</h3>
                            <ul>
                                <li>
                                    <a href="#">Web Design</a>
                                </li>
                                <li>
                                    <a href="#">Web Development</a>
                                </li>
                                <li>
                                    <a href="#">SEO</a>
                                </li>
                            </ul>
                        </div>*@
                </aside>
            </div>
        </div>
    </div>
    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">&copy; @DateTime.Now.Year  <a href="http://www.lylinux.org/" target="_blank" title="逝去日子的博客">Lylinux.org  逝去日子的博客  </a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="full-width.html">Blog</a></li>
                <li><a href="about.html">About</a></li>
                <li><a href="contact.html">Contact</a></li>
            </ul>
        </nav>
    </div>

   

    <link href="~/Content/classyleaves/css/jquery.classyleaves.css" rel="stylesheet" />
    <script src="~/Content/classyleaves/js/jquery.rotate.js"></script>
    <script src="~/Content/classyleaves/js/jquery.classyleaves.js"></script>

    <script>
        //$(document).ready(function () {
        //    var tree = new ClassyLeaves({
        //        leaves: 10,
        //        maxY: -10,
        //        multiplyOnClick: true,
        //        multiply: 2,
        //        infinite: true,
        //        speed: 4000
        //    });
        //    $('body').on('click', '.addLeaf', function () {
        //        console.log('8');
        //        tree.add(8);
        //        return false;
        //    });
        //});
    </script>

</body>
</html>