MVCBlog/MVCBlog.Web/Controllers/AdminController.cs
using MVCBlog.Common.OAuth.Models;
using MVCBlog.Entities.Enums;
using MVCBlog.Entities.Models;
using MVCBlog.Service.Interfaces;
using MVCBlog.Web.CommonHelper;
using MVCBlog.Web.Infrastructure;
using MVCBlog.Web.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MVCBlog.Web.Controllers
{

    public class AdminController : Controller
    {
        private readonly IPostService postService;
        private readonly IUserService userService;
        private readonly ICategoryService categoryService;
        public AdminController(IPostService _postService, IUserService _userService, ICategoryService _categoryService)
        {
            postService = _postService;
            userService = _userService;
            categoryService = _categoryService;
        }
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Register(UserViewModel userinfo)
        {
            if (userService.CheckUserEmail(userinfo.Email))
            {
                ModelState.AddModelError("Email", "该Email已经被注册");
            }
            if (ModelState.IsValid)
            {
                var entity = new UserInfo();
                entity.Name = userinfo.Name;
                entity.Password = userinfo.Password;
                entity.Email = userinfo.Email;
                userService.Insert(entity);
                return RedirectToAction("LogIn");
            }
            return View();
        }
        [HttpGet]
        [AllowAnonymous]
        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn(string email, string password)
        {
            var userinfo = userService.ValidateUser(email, password);
            if (userinfo == null)
            {
                ModelState.AddModelError("", "您输入的帐号或密码错误");
                return View();
            }
            UserDataModel userData = new UserDataModel()
            {
                Id = userinfo.Id,
                Email = userinfo.Email,
                Name = userinfo.Name,
                SystemType = OAuthSystemType.Email,
                Uid = string.Empty,
                AccessToken = string.Empty,
                UserRoles = new List<UserRole>() { userinfo.UserRole }
            };
            UserHelper.SetFormsAuthenticationTicket(email, userData, true);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [AuthorizeRoleAttribute(UserRole.作者)]
        public async Task<ActionResult> PostDeal(int postid = 0)
        {
            var category = await Helper.GetCategorySelectList();
            if (UserHelper.GetLogInUserInfo() == null)
            {
                return RedirectToAction("LogIn");
            }
            PostViewModel model = new PostViewModel();
            if (postid != 0)
            {
                var entity = postService.GetById(postid);
                model.Id = entity.Id;
                model.Content = entity.Content;
                model.Title = entity.Title;
                model.PostStatus = (int)entity.PostStatus;
                model.PostCommentStatus = (int)entity.PostCommentStatus;
                model.CategoryID = entity.PostCategoryInfo.Id;
                model.PostMetasInfos = entity.PostMetasInfos.ToList();
                //model.PostMetasInfos = new List<PostMetasInfo>()
                //{
                //    new PostMetasInfo() { Id = 1, Name = "ff" },
                //        new PostMetasInfo() { Id = 2, Name = "gg" },
                //};
            }
            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult PostDeal(PostViewModel postinfo, IEnumerable<PostMetasInfo> metas)
        {
            if (ModelState.IsValid)
            {
                var entity = new PostInfo();
                entity.Id = postinfo.Id;
                entity.Title = postinfo.Title;
                entity.Content = postinfo.Content;
                entity.PostCategoryInfo = categoryService.GetFromDB(postinfo.CategoryID);
                entity.PostCommentStatus = (PostCommentStatus)postinfo.PostCommentStatus;
                //entity.PostMetasInfos = metas;
                if (metas != null && metas.Count() > 0)
                {
                    var list = metas.ToList();
                    list.RemoveAll(x => string.IsNullOrEmpty(x.Name));
                    entity.PostMetasInfos = list;
                }
                if (entity.Id == 0)
                {
                    postService.Insert(entity, UserHelper.GetLogInUserInfo().Id);
                }
                else
                {
                    entity.PostStatus = (PostStatus)postinfo.PostStatus;
                    postService.Update(entity);
                }
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [AuthorizeRoleAttribute(UserRole.超级管理员)]
        [HttpGet]
        public ActionResult AddCategoryInfo()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public async Task<ActionResult> AddCategoryInfo(CategoryInfo categoryinfo)
        {
            if (ModelState.IsValid)
            {
                categoryinfo.CreateUser = UserHelper.GetLogInUserInfo();
                await categoryService.InsertAsync(categoryinfo, categoryinfo.CreateUser.Id);
                return RedirectToAction("CategoryList");
            }
            return View();
        }
        [Authorize]
        [HttpGet]
        public ActionResult CategoryList()
        {
            var list = categoryService.Query();
            return View(list);
        }

        [Authorize]
        [HttpGet]
        public ActionResult BindAccount()
        {
            if (Request.Cookies["uid"] != null)
            {
                var cookie = new HttpCookie("uid");
                cookie.Expires = DateTime.Now.AddDays(-1);
                Response.Cookies.Add(cookie);
            }
            return View();
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult LogOut()
        {
            UserHelper.UserLogOut();
            return RedirectToAction("Index");
        }
        [Authorize]
        [HttpGet]
        public ActionResult UserList()
        {
            var list = userService.Query(x => !x.IsDelete);
            var infos = list.Select(x => new UserInfoModel()
            {
                Id = x.Id,
                Email = x.Email,
                Name = x.Name,
                UserRole = x.UserRole,
                UserStatus = x.UserStatus,
                CreateTime = x.CreateTime,
                LastLoginTime = x.LastLoginTime
            });
            return View(infos);
        }
    }
}

MVCBlog/MVCBlog.Web/Controllers/CommentController.cs
using MVCBlog.Common;
using MVCBlog.Entities.Models;
using MVCBlog.Service;
using MVCBlog.Service.Interfaces;
using MVCBlog.Web.CommonHelper;
using MVCBlog.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVCBlog.Web.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        private ICommentService commentService;
        private IPostService postService;
        private IUserService userService;
        public CommentController(ICommentService _commentService, IPostService _postService, IUserService _userService)
        {
            commentService = _commentService;
            postService = _postService;
            userService = _userService;
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GetCommentInfo(int postid)
        {
            var res = commentService.Query(x => x.PostID == postid);
            return PartialView(res);
        }
        [HttpGet]
        public ActionResult CommentInfo(int postid)
        {
            var model = new CommentViewModel();
            var loginuser = UserHelper.GetLogInUserInfo();
            model.PostID = postid;
            if (loginuser != null)
            {
                model.UserEmail = loginuser.Email;
                model.UserName = loginuser.Name;
            }
            return PartialView(model);
        }

        [HttpPost]
        public async Task<ActionResult> CommentInfo(CommentViewModel model)
        {
            if (ModelState.IsValid)
            {

                var userinfo = userService.GetUserInfo(model.UserEmail);
                if (userinfo == null)
                {
                    UserInfo u = new UserInfo()
                    {
                        Email = model.UserEmail,
                        Name = model.UserName,
                        Password = ConfigInfo.UserDefaultPassword
                    };
                    await userService.InsertAsync(u, 0);
                    userinfo = await userService.GetUserInfoAsync(model.UserEmail);
                }
                var postinfo = postService.GetById(model.PostID);
                postinfo.CommentCount += 1;
                await postService.UpdateAsync(postinfo);
                var commentinfo = new CommentInfo()
                {
                    CommentUser = userinfo,
                    PostID = model.PostID,
                    CommentContent = model.CommentContent,
                    CommentTitle = model.CommentTitle
                };
                commentService.Insert(commentinfo);
                return RedirectToAction("PostInfo", "PostInfo", new { id = model.PostID });
            }
            return View();
        }
    }
}

MVCBlog/MVCBlog.Web/Controllers/PostInfoController.cs
using MVCBlog.Common;
using MVCBlog.Entities.Models;
using MVCBlog.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVCBlog.Web.Controllers
{
    [AllowAnonymous]
    public class PostInfoController : Controller
    {
        private readonly IPostService postService;
        private readonly IUserService userService;
        private readonly ICategoryService categoryService;
        public PostInfoController(IPostService _postService, IUserService _userService, ICategoryService _categoryService)
        {
            postService = _postService;
            userService = _userService;
            categoryService = _categoryService;
        }
        // GET: PostInfo
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult RecentPost()
        {
            var recentpost = postService.GetRecentPost(ConfigInfo.RecentPostCount);
            return PartialView(recentpost);
        }

        public ActionResult PostCategoryInfo()
        {
            var categorylist = categoryService.Query();
            return PartialView(categorylist);
        }

        public ActionResult PostInfo(int id)
        {
            var entity = postService.GetById(id);
            return View(entity);
        }

        public ActionResult PostMonthList()
        {
            var posttimes = postService.GetPostMonthInfos();
            var times = posttimes.Select(x => x.ToString("yyyy-MM")).Distinct();
            return PartialView(times);
        }
        public ActionResult PostMonthInfo(int year, int month, int index = 1)
        {
            var postinfo = postService.Query(index, ConfigInfo.PageCount, x => x.CreateTime.Year == year && x.CreateTime.Month == month);
            return View(postinfo);
        }

        public ActionResult PostMetaInfo(PostInfo info)
        {
            return PartialView(info);
        }
    }
}

MVCBlog/MVCBlog.Web/Controllers/UserController.cs
using MVCBlog.Common;
using MVCBlog.Entities.Models;
using MVCBlog.Service;
using MVCBlog.Service.Interfaces;
using MVCBlog.Web.CommonHelper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVCBlog.Web.Controllers
{
    //[Authorize]
    public class UserController : Controller
    {
        private IUserService userService;
        private IPostService postService;
        public UserController(IUserService _userService, IPostService _postService)
        {
            userService = _userService;
            postService = _postService;
        }

        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserList()
        {
            return View();
        }

        public ActionResult UserWightInfo()
        {
            UserInfo userinfo = UserHelper.GetLogInUserInfo();
            if (userinfo != null)
            {
                return PartialView(userinfo);
            }
            return PartialView();
        }

        public ActionResult UserPostInfo(int userid, int index = 1)
        {
            var postinfos = postService.Query(index, ConfigInfo.PageCount, x => x.PostAuthor.Id == userid);
            return View(postinfos);
        }
    }
}

MVCBlog/MVCBlog.Web/Views/PostInfo/PostCategoryInfo.cshtml
@model IEnumerable<MVCBlog.Entities.Models.CategoryInfo>


<div class="widget widget-category">
    <h3 class="widget-title">Category</h3>
    <ul>
        @if (Model != null && Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <li>
                    <a href="#">@item.CategoryName</a>
            </li>
            }
        }
    </ul>
</div>

MVCBlog/MVCBlog.Web/Views/PostInfo/PostInfo.cshtml
@model MVCBlog.Entities.Models.PostInfo
@using MVCBlog.Common;
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="col-md-8">
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">@Model.Title</h1>
            @Html.Action("PostMetaInfo", "PostInfo", Model)
            @*<div class="entry-meta">
                    <span class="post-category"><a href="#">@Model.PostCategoryInfo.CategoryName</a></span>

                    <span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">@Model.CreateTime.ToString(ConfigInfo.TimeFormat)</time></a></span>

                    <span class="post-author"><a href="@Url.Action("UserPostInfo", "User", new { userid = Model.PostAuthor.Id })">@Model.PostAuthor.Name</a></span>
                    @if (HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        <span class="post-category"><a href="@Url.Action("PostDeal", "Admin", new { postid = Model.Id })">编辑</a></span>
                    }
                    <span class="comments-link"><a href="#">@Model.CommentCount Comments</a></span>

                </div>*@
        </header>

        <div class="entry-content clearfix">
            @Html.Raw(Model.Content)
        </div>
    </article>

</main>
<div class="col-md-8">
    @if (Model.PostCommentStatus != MVCBlog.Entities.Enums.PostCommentStatus.关闭)
    {
        @Html.Action("GetCommentInfo", "Comment", new { postid = Model.Id })
        @Html.Action("CommentInfo", "Comment", new { postid = Model.Id })
    }
    else
    {
        <span>该文章评论已关闭</span>
    }

</div>

MVCBlog/MVCBlog.Web/Views/PostInfo/PostMetaInfo.cshtml
@model MVCBlog.Entities.Models.PostInfo
@using MVCBlog.Common;
<div class="entry-meta">
    <span class="post-category"><a href="#">@Model.PostCategoryInfo.CategoryName</a></span>

    <span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">@Model.CreateTime.ToString(ConfigInfo.TimeFormat)</time></a></span>

    <span class="post-author"><a href="@Url.Action("UserPostInfo", "User", new { userid = Model.PostAuthor.Id })">@Model.PostAuthor.Name</a></span>
    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        <span class="post-category"><a href="@Url.Action("PostDeal", "Admin", new { postid = Model.Id })">编辑</a></span>
    }
    <span class="comments-link"><a href="#">@Model.CommentCount Comments</a></span>

    @if (Model.PostMetasInfos != null && Model.PostMetasInfos.Count() > 0)
    {
        <span class="post-category">

        </span>
        <span> 文章标签</span>
        @Html.Raw(string.Join(",", Model.PostMetasInfos.Select(x => string.Format("<a href='#'>{0}</a>", x.Name))))
    }

</div>

MVCBlog/MVCBlog.Web/Views/PostInfo/PostMonthList.cshtml
@model IEnumerable<string>


@if (Model != null && Model.Count() > 0)
{
    <div class="widget widget-recent-posts">
        <h3 class="widget-title">Recent Posts</h3>
        <ul>
            @foreach (var item in Model)
            {
                var year = item.Split('-')[0];
                var month = item.Split('-')[1];
                <li>
                    <a href="@Url.Action("PostMonthInfo", "PostInfo", new { year = year, month = month })">@string.Format("{0}年{1}月", year, month)</a>
                </li>
            }
        </ul>
    </div>
}

MVCBlog/MVCBlog.Web/Views/PostInfo/RecentPost.cshtml
@model IEnumerable<MVCBlog.Entities.Models.PostInfo>


@if (Model != null && Model.Count() > 0)
{
    <div class="widget widget-recent-posts">
        <h3 class="widget-title">Recent Posts</h3>
        <ul>
            @foreach (var item in Model)
            {
                <li>
                    <a href="#">@item.Title</a>
                </li>
            }
        </ul>
    </div>
}